trigger:
- main  # Ensure this matches the branch name in your GitHub repository

stages:
- stage: Build # Define a build stage
  jobs:
  - job: BuildTests # Define a job within the build stage
    pool: # Define the agent pool to run the job on
      vmImage: 'ubuntu-latest'
    steps:
    - script: mvn clean install # Run maven clean and install commands
      displayName: 'Build and Install Tests'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        
- stage: Test # Define a test stage
  dependsOn: Build # Define dependency on the Build stage
  jobs:
  - job: RunTests # Define a job within the test stage
    pool: # Define the agent pool to run the job on
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: 'drop'
      displayName: 'Download Artifact'
    - script: mvn test # Run maven test command to execute regression tests
      displayName: 'Run Regression Tests'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '$(System.DefaultWorkingDirectory)/target/surefire-reports/*.xml'
        testRunTitle: 'Maven Test Results'
